theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup.highlight]
codeFences = false


[markup.goldmark.renderer]
unsafe=true

[params.reveal_hugo]
history = true
custom_theme = "reveal-hugo/themes/robot-lung.css"
highlight_theme = "atom-one-dark-reasonable"

[reveal_hugo.plugins]
["plugin/gallery/gallery.plugin.js"]
